#!/usr/bin/env python3
"""
Generate weekly architecture compliance report.
Outputs markdown format for GitHub issues or team updates.

Usage: python scripts/generate-weekly-report.py
"""

import json
import subprocess
from datetime import datetime, timedelta
from pathlib import Path

def run_script(script_path: str) -> dict:
    """Run the metrics collection script and parse JSON output."""
    try:
        result = subprocess.run(
            ['python', str(script_path)],
            capture_output=True,
            text=True,
            cwd=Path(__file__).parent
        )
        if result.returncode == 0:
            return json.loads(result.stdout)
        else:
            return {}
    except Exception as e:
        print(f"Error running metrics script: {e}")
        return {}

def generate_report(metrics: dict) -> str:
    """Generate markdown report from metrics."""
    report_date = datetime.now().strftime('%Y-%m-%d')
    week_start = (datetime.now() - timedelta(days=datetime.now().weekday())).strftime('%Y-%m-%d')
    
    report = f"""# 🛡️ Architecture Compliance Weekly Report

**Report Date:** {report_date}  
**Week of:** {week_start}

---

## 📊 Summary

| Metric | Value | Trend |
|--------|-------|-------|
| **Total violations** | {metrics.get('total_violations', 0)} | - |
| **Violations this week** | {metrics.get('violations_this_week', 0)} | {metrics.get('trend', 'stable')} |
| **Violations this month** | {metrics.get('violations_this_month', 0)} | - |
| **Open violations** | {metrics.get('open_violations', 0)} | - |
| **Closed violations** | {metrics.get('closed_violations', 0)} | - |
| **Compliance rate** | {metrics.get('compliance_rate', 100):.1f}% | - |

---

## 🔥 Top Violations by Type

"""
    
    by_type = metrics.get('by_type', {})
    if by_type:
        report += "| Type | Count |\n"
        report += "|------|-------|\n"
        for vtype, count in sorted(by_type.items(), key=lambda x: x[1], reverse=True)[:10]:
            report += f"| {vtype} | {count} |\n"
    else:
        report += "*No violations recorded this period.*\n"
    
    report += "\n---\n\n## 👥 Top Offenders (Files)\n\n"
    
    by_file = metrics.get('by_file', {})
    if by_file:
        report += "| File | Violations |\n"
        report += "|------|------------|\n"
        for fpath, count in sorted(by_file.items(), key=lambda x: x[1], reverse=True)[:10]:
            report += f"| `{fpath}` | {count} |\n"
    else:
        report += "*No violations recorded this period.*\n"
    
    report += "\n---\n\n## 📈 Violations by Branch\n\n"
    
    by_branch = metrics.get('by_branch', {})
    if by_branch:
        report += "| Branch | Violations |\n"
        report += "|--------|------------|\n"
        for branch, count in sorted(by_branch.items(), key=lambda x: x[1], reverse=True):
            report += f"| `{branch}` | {count} |\n"
    else:
        report += "*No violations recorded this period.*\n"
    
    report += "\n---\n\n## 🕐 Recent Violations\n\n"
    
    recent = metrics.get('recent_violations', [])
    if recent:
        report += "| Date | Type | File | User | Status |\n"
        report += "|------|------|------|------|--------|\n"
        for v in reversed(recent[-10:]):
            date = v.get('timestamp', 'Unknown')[:10]
            vtype = v.get('violation_type', 'Unknown')
            fpath = v.get('file_path', 'Unknown')
            user = v.get('user_name', 'Unknown')
            status = v.get('status', 'OPEN')
            report += f"| {date} | {vtype} | `{fpath}` | {user} | {status} |\n"
    else:
        report += "*No violations recorded this period.*\n"
    
    report += f"""
---

## ✅ Action Items

- [ ] Review top 3 violation types and identify patterns
- [ ] Update auto-fix script for common violation patterns
- [ ] Notify team if escalation threshold reached (5+ violations/week)
- [ ] Close resolved violations in log
- [ ] Share report with architecture team

---

## 📝 Notes

*Auto-generated by architecture guardrails on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*

**Next report:** {(datetime.now() + timedelta(days=7)).strftime('%Y-%m-%d')}

---

**Related:**
- Issue #81: Telemetry & escalation for architecture violations
- Documentation: `docs/04-sops/06-branch-protection-config.md`
- Violation log: `.github/architecture-violations.log`
"""
    
    return report

def main():
    repo_root = Path(__file__).parent.parent
    metrics_script = str(repo_root / 'scripts' / 'collect-architecture-metrics.py')
    
    print("📊 Collecting architecture compliance metrics...")
    metrics = run_script(metrics_script)
    
    if not metrics:
        print("⚠️  No metrics available - violation log may be empty")
        print("\n# Architecture Compliance Weekly Report\n")
        print("*No violations recorded this period.*\n")
        return
    
    print("✅ Metrics collected")
    print("\n" + "="*60)
    print(generate_report(metrics))
    print("="*60)

if __name__ == '__main__':
    main()
