#!/usr/bin/env bash
# Generate TypeScript types from backend OpenAPI spec
#
# Usage:
#   ./scripts/generate-api-types.sh <backend-url> <output-path>
#   ./scripts/generate-api-types.sh http://localhost:8080/v3/api-docs boilerplate/reactjs/src/generated/api.ts
#
# Environment:
#   API_BASE_URL — base URL of backend (default: http://localhost:8080)
#
# Called by: npm run generate:api-types (frontend package.json)
#            CI workflow (backend PR merge)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
API_BASE_URL="${API_BASE_URL:-http://localhost:8080}"
BACKEND_URL="${1:-${API_BASE_URL}/v3/api-docs}"
OUTPUT_PATH="${2:-src/generated/api.ts}"

echo "🔧 Generating TypeScript types from OpenAPI spec..."
echo "   Backend: ${BACKEND_URL}"
echo "   Output:  ${OUTPUT_PATH}"

# Ensure output directory exists
OUTPUT_DIR="$(dirname "${OUTPUT_PATH}")"
mkdir -p "${OUTPUT_DIR}"

# Check if openapi-typescript is available
if ! command -v openapi-typescript >/devdev/null 2>&1; then
    echo "❌ openapi-typescript not found. Install with:"
    echo "   npm install -g openapi-typescript"
    exit 1
fi

# Generate types (tolerate backend being unavailable for offline usage)
if curl -sf "${BACKEND_URL}" >/dev/null 2>&1; then
    openapi-typescript "${BACKEND_URL}" -o "${OUTPUT_PATH}"
    echo "✅ Types generated from live backend"
else
    echo "⚠️  Backend not reachable at ${BACKEND_URL}"
    echo "   If a cached OpenAPI JSON exists, it will be used."
    echo "   To force generation, start the backend first."
    if [ -f "${OUTPUT_PATH}" ]; then
        echo "   Keeping existing types (not regenerated)"
    else
        echo "   No existing types found. Creating stub..."
        cat > "${OUTPUT_PATH}" <<'EOF'
/**
 * @file API Type Definitions (OpenAPI → TypeScript)
 *
 * This file is auto-generated by openapi-typescript from the backend OpenAPI spec.
 * DO NOT EDIT MANUALLY — run `npm run generate:api-types` to regenerate.
 *
 * Source: Backend /v3/api-docs endpoint
 * Tool: openapi-typescript
 */

// Placeholder — backend was unreachable during generation.
// Run `npm run generate:api-types` with the backend running to populate.
export type ApiTypes = Record<string, unknown>;
EOF
    fi
    exit 0
fi

# Post-generation: add header comment
echo "📝 Adding generation header..."
GENERATED_HEADER="/**
 * @file API Type Definitions (OpenAPI → TypeScript)
 *
 * AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
 * Source: ${BACKEND_URL}
 * Tool: openapi-typescript
 * Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)
 *
 * To regenerate:
 *   npm run generate:api-types
 *   or: ./scripts/generate-api-types.sh
 */

"

# Prepend header to generated file
TMP_FILE="$(mktemp)"
echo "${GENERATED_HEADER}" > "${TMP_FILE}"
cat "${OUTPUT_PATH}" >> "${TMP_FILE}"
mv "${TMP_FILE}" "${OUTPUT_PATH}"

echo "✅ API types ready at ${OUTPUT_PATH}"
