version: '3.8'

services:
  {{ cookiecutter.project_slug }}:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PYTHONUNBUFFERED=1
{%- if cookiecutter.use_postgres == "yes" %}
    depends_on:
      - postgres
{%- endif %}

{%- if cookiecutter.use_postgres == "yes" %}
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER={{ cookiecutter.package_name }}_user
      - POSTGRES_PASSWORD={{ cookiecutter.package_name }}_pass
      - POSTGRES_DB={{ cookiecutter.package_name }}s
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
{%- endif %}
